import Link from "next/link";
import { LOGO, MARK_PATH, WORDMARK_PATH } from "@/lib/brand/logo";
import { MAKER_NAME, MAKER_URL } from "@/lib/site";

/* The logo, as artwork rather than as styled text.
 *
 * It used to be the string "DuctForge" with a coloured span, which is not a
 * logo — it depends on Satoshi having loaded, it cannot leave the page, and
 * two-tone type is not what DebugSwift's own lockup does.
 *
 * The wordmark here is Satoshi Bold OUTLINED, generated by
 * scripts/make-logo.mjs from the font's glyf table and checked in as path data.
 * That is the same artwork as public/brand/ductforge.svg and the PNGs beside
 * it — one source, several formats.
 *
 * WHY INLINE SVG AND NOT `<img>`. An image cannot take the page's colour, so a
 * logo shipped as a file needs a second file for dark mode and a swap between
 * them. Inlined, it is `currentColor`: one asset, correct in both themes,
 * correct at any zoom, and no extra request. The standalone files still exist
 * for everywhere the logo travels without our stylesheet.
 *
 * Two sibling links, never nested — an anchor inside an anchor is invalid and
 * browsers resolve it unpredictably. The name goes home; the byline goes to
 * DebugSwift.
 */

const HEIGHTS = { sm: 26, md: 34 } as const;

export default function Wordmark({ size = "md" }: { size?: keyof typeof HEIGHTS }) {
  const height = HEIGHTS[size];
  const width = Math.round((LOGO.width / LOGO.height) * height);

  return (
    <span className="flex flex-col gap-0.5 leading-tight">
      <Link href="/" className="inline-flex text-accent" aria-label="DuctForge, home">
        <svg
          viewBox={LOGO.viewBox}
          width={width}
          height={height}
          role="img"
          aria-hidden="true"
          focusable="false"
          fill="currentColor"
        >
          <path d={MARK_PATH} transform={`scale(${LOGO.markSize / 100})`} />
          <path d={WORDMARK_PATH} transform={`translate(${LOGO.markSize + LOGO.gap} ${LOGO.baseline})`} />
        </svg>
      </Link>
      <a
        href={MAKER_URL}
        className="whitespace-nowrap text-small text-muted underline-offset-2 transition-colors duration-200 ease-out hover:text-body hover:underline"
      >
        by {MAKER_NAME}
      </a>
    </span>
  );
}
