/* Icon generation. Run with `npm run icons` after changing the mark.
 *
 * The app needs real raster icons — a favicon.ico for the browsers and
 * bookmark bars that still ignore SVG, an apple-touch-icon, and PNGs for the
 * web manifest including a maskable one. Every off-the-shelf way to produce
 * those is a native binary dependency, for a job that is one rounded rectangle
 * and one elbow: see scripts/raster.mjs for why that is not worth taking on.
 *
 * The mark comes from scripts/mark.mjs, which the logo generator also uses, so
 * the tab icon and the wordmark's mark are the same shape by construction
 * rather than by somebody remembering. They were not, once.
 *
 * Output is checked in. The build never runs this.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
  CREAM,
  INDIGO,
  MARK_FILL_RULE,
  MARK_PATH,
  TILE_INSET,
  TILE_RADIUS,
  insetFor,
  roundedRect,
} from "./mark.mjs";
import { encodeIco, encodePng, parsePath, rasterise, transform } from "./raster.mjs";

const ROOT = new URL("../", import.meta.url);
const out = (p) => fileURLToPath(new URL(p, ROOT));

const mark = parsePath(MARK_PATH);

/**
 * One square icon.
 *
 * `rounded` off with a bigger inset is the maskable variant: Android crops a
 * maskable icon to whatever shape the launcher uses, so it has to bleed to the
 * edges and keep the mark inside the middle 80%.
 */
function icon(size, { rounded = true, inset = insetFor(size) } = {}) {
  const pad = size * inset;
  const inner = size - pad * 2;
  const shapes = [];

  if (rounded) {
    shapes.push({
      contours: parsePath(roundedRect(size, size * TILE_RADIUS)),
      color: INDIGO,
    });
  } else {
    shapes.push({ contours: parsePath(roundedRect(size, 0)), color: INDIGO });
  }
  shapes.push({
    contours: transform(mark, { sx: inner / 100, tx: pad, ty: pad }),
    color: CREAM,
    /* The mark's flange joints are the SPACE BETWEEN its three subpaths, so
     * the indigo tile shows through them with no help — see mark.mjs. The rule
     * is stated anyway because an earlier mark cut its joints as holes and did
     * depend on it, and because the wrong fix for a joint that will not show —
     * painting it in the ground colour on top — would put cream slashes across
     * every icon we ship. */
    rule: "evenodd",
  });

  return encodePng(size, size, rasterise({ width: size, height: size, shapes }));
}

mkdirSync(out("public/icons"), { recursive: true });

const files = [
  ["app/apple-icon.png", icon(180)],
  ["public/icons/icon-192.png", icon(192)],
  ["public/icons/icon-512.png", icon(512)],
  ["public/icons/icon-maskable-512.png", icon(512, { rounded: false, inset: 0.23 })],
];

for (const [path, buf] of files) {
  writeFileSync(out(path), buf);
  console.log(`${path}  ${buf.length} bytes`);
}

/* 16, 32 and 48 in one file, each with the optical inset `insetFor` gives it. */
const ico = encodeIco([16, 32, 48].map((size) => ({ size, png: icon(size) })));
writeFileSync(out("app/favicon.ico"), ico);
console.log(`app/favicon.ico  ${ico.length} bytes (16, 32, 48)`);

/* app/icon.svg is GENERATED now, and that is a bug fix.
 *
 * It used to be hand-written with a pasted copy of the path and a comment
 * asking whoever changed the mark to please paste the new one. Nobody did:
 * when this ran, the favicon, the printed sheet and the OG card were carrying
 * three DIFFERENT marks, two of them versions the app had already moved on
 * from. A comment is not a mechanism. */
writeFileSync(
  out("app/icon.svg"),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <!--
    GENERATED by scripts/make-icons.mjs from scripts/mark.mjs. Do not edit:
    run \`npm run brand\`. Indigo 500 ground, Cream mark, both from the token
    table. The flange joints are the space between the mark's subpaths, so the
    ground shows through them.
  -->
  <rect width="100" height="100" rx="${TILE_RADIUS * 100}" fill="${INDIGO}" />
  <path
    d="${MARK_PATH}"
    fill-rule="${MARK_FILL_RULE}"
    transform="translate(${TILE_INSET} ${TILE_INSET}) scale(${((100 - TILE_INSET * 2) / 100).toFixed(4)})"
    fill="${CREAM}"
  />
</svg>
`,
);
console.log(`app/icon.svg  generated`);
